apiVersion : v1
kind: Pod
metadata :
  labels:
    env : prod
    app : main
    tier : fronted
    owner : PavelProsvetov
  name: my-web
spec:
  containers:
    - name : container-apache
      image: nginx:latest
      ports:
        - containerPort: 80